swagger: "2.0"
info:
  description: |
    An API used to create and query information about import jobs. This API is seperated into two parts;
    * The external interface is used by florence to create and query for information about an import job
    * The internal interface is used by services which are processing the import job. The services will use this API to update the state and add events to the job.
  version: "1.0.0"
  title: "ONS Import API"
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
tags:
- name: "External Interface"
- name: "Internal Interface"
schemes:
- "http"
parameters:
  instanceId:
    name: instanceId
    description: "A unique id for an instance"
    type: string
    in: path
    required: true
  jobId:
    name: jobId
    description: "A unique jobId"
    type: string
    in: path
    required: true
  newJob:
    name: newJob
    in: body
    schema:
      $ref: '#/definitions/NewJob'
    required: true
  dimension:
    name: Dimension
    description: "A dimension of an observation to store"
    in: body
    schema:
      $ref: '#/definitions/Dimension'
    required: true
  file:
    name: File
    description: "A file to include in the job"
    in: body
    schema:
      $ref: '#/definitions/File'
    required: true
  event:
    name: event
    description: "An import event when publishing a dataset"
    in: body
    schema:
      $ref: '#/definitions/InstanceEvent'
    required: true
  state:
    name: state
    description: "The state of an import job"
    in: body
    schema:
      $ref: '#/definitions/State'
    required: true
  nodeId:
    name: nodeId
    description: "A node id"
    in: body
    schema:
      $ref: '#/definitions/NodeId'
    required: true
  nodeName:
    name: nodeName
    description: "The name of a node (instanceId-Type.Value)"
    type: string
    in: path
    required: true
  observation:
    name: observation
    description: "The number of observations within an instance"
    in: body
    schema:
      $ref: '#/definitions/Observation'
    required: true
securityDefinitions:
  FlorenceAPIKey:
    description: "API key used to allow florence users to create and query the progress of importing a dataset"
    type: apiKey
    in: header
    name: florence-token
  InternalAPIKey:
    description: "API key used to allow only internal services to update the state of an import job"
    type: apiKey
    in: header
    name: internal-token
paths:
  /jobs:
    post:
      tags:
      - "External Interface"
      summary: "Create an import job"
      description: |
        To import a dataset a job must be created first. To do this a data baker recipe is needed and the number of instances which the recipe creates. Once a job is created files can be added to the job and the state of the job can be changed.
      produces:
      - "application/json"
      parameters:
      - $ref: '#/parameters/newJob'
      security:
      - FlorenceAPIKey: []
      responses:
        200:
          description: "An import job was successfully created"
          schema:
            $ref: '#/definitions/Job'
        400:
          description: "Invalid json message was sent to the API"
        500:
          description: "Failed to process the request due to an internal error"
  /jobs/{jobId}/file:
    put:
      tags:
      - "External Interface"
      summary: "Add a file into a job"
      description: "Add a file into a job, for each file added an alias name needs to be given. This name needs to link to the recipe"
      parameters:
      - $ref: '#/parameters/jobId'
      - $ref: '#/parameters/file'
      produces:
      - "application/json"
      security:
      - FlorenceAPIKey: []
      responses:
        200:
          description: "The file was added to the import job"
        400:
          description: "Invalid json message was sent to the API"
        404:
          description: "JobId does not match any import jobs"
        500:
          description: "Failed to process the request due to an internal error"
  /jobs/{jobId}/state:
    put:
      tags:
      - "External Interface"
      summary: "Update the jobs state"
      description: |
        Update the state of the job. If this is set to submitted, this shall trigger the
        import process.
      parameters:
      - $ref: '#/parameters/jobId'
      - $ref: '#/parameters/state'
      produces:
      - "application/json"
      security:
      - FlorenceAPIKey: []
      responses:
        200:
          description: "The job is in a queue"
        400:
          description: "Invalid json message was sent to the API"
        404:
          description: "JobId does not match any import jobs"
        500:
          description: "Failed to process the request due to an internal error"
  /instances/{instanceId}:
    get:
      tags:
      - "External Interface"
      summary: "Get Information about an instance"
      description: "Get the current state of an instance, this includes all events which have happened."
      parameters:
      - $ref: '#/parameters/instanceId'
      produces:
      - "application/json"
      security:
      - FlorenceAPIKey: []
      responses:
        200:
          description: "Return a single instance state"
          schema:
            $ref: '#/definitions/InstanceState'
        404:
          description: "InstanceId does not match any import jobs"
        500:
          description: "Failed to process the request due to an internal error"
  /instances/{instanceId}/events:
    put:
      tags:
       - "Internal Interface"
      summary: "Add an event to an instance"
      description: |
        Add a new event into an instance. Events can be for information or error messages.
        Each event must contain a type of event (Info or Error), a message to explain
        the event, time of the event and finally the message offset in kafka
      parameters:
      - $ref: '#/parameters/instanceId'
      - $ref: '#/parameters/event'
      security:
      - InternalAPIKey: []
      responses:
        200:
          description: "The event was added to the instance"
        400:
          description: "Invalid json message sent"
        404:
          description: "InstanceId does not match any instances"
        500:
          description: "Failed to process the request due to an internal error"
  /instances/{instanceId}/observation:
    put:
      tags:
      - "Internal Interface"
      summary: "Update the number of observations within this instance"
      description: "Update the number of observations within this instance"
      parameters:
      - $ref: '#/parameters/instanceId'
      - $ref: '#/parameters/observation'
      security:
      - InternalAPIKey: []
      responses:
        200:
          description: "The event was added to the instance"
        400:
          description: "Invalid json message sent"
        404:
          description: "InstanceId does not match any instances"
        500:
          description: "Failed to process the request due to an internal error"
  /instances/{instanceId}/dimensions:
    put:
      tags:
      - "Internal Interface"
      summary: "Add a dimension for the instance"
      description: |
        Add a dimension from the observations found in the V3 data. To create a dimension the following items are needed;
        * nodeName - The name of the node eg (instanceId)-(dimension).(value)
        * value - The value of the observation
      parameters:
      - $ref: '#/parameters/instanceId'
      - $ref: '#/parameters/dimension'
      produces:
      - "application/json"
      security:
      - InternalAPIKey: []
      responses:
        200:
          description: "The dimension was added"
        404:
          description: "InstanceId does not match any instances"
        500:
          description: "Failed to process the request due to an internal error"
    get:
      tags:
      - "Internal Interface"
      summary: "Get all dimensions from an instance"
      description: "Get all dimensions from an instance"
      parameters:
      - $ref: '#/parameters/instanceId'
      produces:
      - "application/json"
      security:
      - InternalAPIKey: []
      responses:
        200:
          description: "Return a list of dimensions"
          schema:
            $ref: '#/definitions/Dimensions'
        404:
          description: "InstanceId does not match any instances"
        500:
          description: "Failed to process the request due to an internal error"
  /instances/{instanceId}/dimensions/{nodeName}/nodeId:
    put:
      tags:
      - "Internal Interface"
      summary: "Update a dimension with the nodeId"
      description: |
        Update the dimension with a nodeId
      parameters:
      - $ref: '#/parameters/instanceId'
      - $ref: '#/parameters/nodeName'
      - $ref: '#/parameters/nodeId'
      produces:
      - "application/json"
      security:
      - InternalAPIKey: []
      responses:
        200:
          description: "Updated the dimension with the nodeId"
        404:
          description: "InstanceId does not match any instances"
        500:
          description: "Failed to process the request due to an internal error"
definitions:
  Job:
    type: object
    description: "An object returned when an import job is created"
    properties:
      jobId:
        type: string
        description: "A unique id for an import job"
      instanceIds:
        type: array
        items:
          type: string
  NewJob:
    type: object
    description: "An object used to create a job"
    properties:
      recipe:
        type: string
        description: "The type of recipe to use when baking the data"
      numberOfInstances:
        type: integer
  InstanceState:
    type: object
    properties:
      instanceId:
        type: string
        description: "A unique id for a job"
      state:
        type: string
        description: |
          The state of the import job
      events:
        type: array
        description: "A list of events took place for this job"
        items:
          $ref: '#/definitions/InstanceEvent'
      numberOfObservations:
        type: integer
        description: "The number of observations in this instance"
      lastUpdated:
        type: string
        description: "The last time an event happened"
  InstanceEvent:
    type: object
    properties:
      type:
        type: string
        description: |
          The type of event, this can be;
          * Info - for an information event
          * Error - for an error event
      time:
        type: string
        description: "The time of the event in ISO 8601 format"
      message:
        type: string
        description: "A description of the event"
      messageOffset:
        type: string
        description: "The kafka message offset (Used to locate the kafka message)"
  State:
    type: object
    description: "A object used to update the state of an import job"
    properties:
      state:
        type: string
        description: |
          The state to set the job
  Dimension:
    type: object
    description: "A dimension object"
    properties:
      nodeName:
        description: "The name of the node (instanceId-dimension.value)."
        type: string
      value:
        description: "The value of the dimension"
        type: string
  Dimensions:
    type: object
    properties:
      instanceId:
        type: string
        description: "The instanceId of the import job"
      items:
        type: array
        description: "A list of all dimensions within an import job"
        items:
          $ref: '#/definitions/Dimension'
  NodeId:
    type: object
    properties:
      nodeId:
        description: "Graph database node Id"
        type: string
  File:
    type: object
    properties:
      aliasName:
        description: "An alias name for the file"
        type: string
      url:
        description: "The full S3 path including zone, and bucket"
        type: string
  Observation:
    type: object
    description: "A model used to update the number of observations within an instance"
    properties:
      numberOfObservations:
        type: integer
        description: "The number of observations within an instance"