swagger: "2.0"
info:
  description: |
    An API used to create and query information about imports. This API is seperated into two parts;
    * The external interface is used by florence to create and query for information about an import job
    * The internal interface is used by services which are processing the import job. The services will uses this API to update the state and add events to the job.
  version: "1.0.0"
  title: "ONS Import API"
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
tags:
- name: "External Interface"
- name: "Internal Interface"
schemes:
- "http"
parameters:
  instanceId:
    name: instanceId
    description: "A unique instanceId that relates to an import job"
    type: string
    in: path
    required: true
  importJob:
    name: importJob
    in: body
    schema:
      $ref: '#/definitions/ImportJob'
    required: true
  dimension:
    name: Dimension
    description: "A dimension of an observation to store"
    in: body
    schema:
      $ref: '#/definitions/Dimension'
    required: true
  s3File:
    name: S3File
    description: "A S3 file to include in the import job"
    in: body
    schema:
      $ref: '#/definitions/S3File'
  pageSize:
    name: pageSize
    description: "Pagination size for the number of import jobs returned"
    in: query
    type: integer
    required: true
  pageNumber:
    name: pageNumber
    description: "Pagination page number"
    in: query
    type: integer
    required: true
  event:
    name: event
    description: "An import event when publishing a dataset"
    in: body
    schema:
      $ref: '#/definitions/ImportEvent'
    required: true
  state:
    name: state
    description: "The state of an import job"
    in: body
    schema:
      $ref: '#/definitions/State'
    required: true
securityDefinitions:
  FlorenceAPIKey:
    description: "API key used to allow florence users to create and query the progress of importing a dataset"
    type: apiKey
    in: header
    name: florence-token
  InternalAPIKey:
    description: "API key used to allow only internal services to update the state of an import job"
    type: apiKey
    in: header
    name: internal-token
paths:
  /import:
    post:
      tags:
      - "External Interface"
      summary: "Create an import job"
      description: |
        To generate a dataset a single or multiple files are required. Each file must be store in S3 and the full S3 path must be provided
        in the body of the message. A name, edition and a version for the dataset must all be provided.
      produces:
      - "application/json"
      parameters:
      - $ref: '#/parameters/importJob'
      security:
      - FlorenceAPIKey: []
      responses:
        200:
          description: "A import job was successfully created"
          schema:
            $ref: '#/definitions/JobInstance'
        400:
          description: "Invalid json message was sent to the API"
        500:
          description: "Failed to process the request due to an internal error"
    get:
      tags:
      - "External Interface"
      summary: "Get a list of all import jobs"
      description: "Returns a list of all import jobs, pagination is used to control the amount of results returned to the client"
      produces:
      - "application/json"
      parameters:
      - $ref: '#/parameters/pageSize'
      - $ref: '#/parameters/pageNumber'
      security:
      - FlorenceAPIKey: []
      responses:
        200:
          description: "A paginated list of import jobs"
          schema:
            $ref: '#/definitions/ImportJobStates'
        400:
          description: "Request is missing required parameters"
        500:
          description: "Failed to process the request due to an internal error"
  /import/{instanceId}:
    get:
      tags:
      - "External Interface"
      summary: "Get Information about an import job"
      description: "Get the current state of an import job, this includes all events which have happened and a overall state of the job."
      parameters:
      - $ref: '#/parameters/instanceId'
      produces:
      - "application/json"
      security:
      - FlorenceAPIKey: []
      responses:
        200:
          description: "Return a single import job"
          schema:
            $ref: '#/definitions/ImportJobState'
        404:
          description: "InstanceId does not match any import jobs"
        500:
          description: "Failed to process the request due to an internal error"
  /import/{instanceId}/s3file:
    put:
      tags:
      - "External Interface"
      summary: "Add a file to the import job"
      description: "Add a file into the import job"
      parameters:
      - $ref: '#/parameters/instanceId'
      - $ref: '#/parameters/s3File'
      produces:
      - "application/json"
      security:
      - FlorenceAPIKey: []
      responses:
        200:
          description: "The file was added to the import job"
        400:
          description: "Invalid json message was sent to the API"
        404:
          description: "InstanceId does not match any import jobs"
        500:
          description: "Failed to process the request due to an internal error"
  /import/{instanceId}/start:
    post:
      tags:
      - "External Interface"
      summary: "Start importing the dataset"
      description: "Once this is called the import job is placed into a queue to be proccessed"
      parameters:
      - $ref: '#/parameters/instanceId'
      produces:
      - "application/json"
      security:
      - FlorenceAPIKey: []
      responses:
        200:
          description: "The import job is in a queue"
        400:
          description: "Invalid json message was sent to the API"
        404:
          description: "InstanceId does not match any import jobs"
        500:
          description: "Failed to process the request due to an internal error"
  /import/{instanceId}/events:
    put:
      tags:
       - "Internal Interface"
      summary: "Add an event to a import job"
      description: |
        Add a new event onto the import job. Events can be for information or error messages. Each event must contain a
        type of event(Info or Error), a message to explaining the event, time of the event and finally the
        message offset in kafka
      parameters:
      - $ref: '#/parameters/instanceId'
      - $ref: '#/parameters/event'
      security:
      - InternalAPIKey: []
      responses:
        200:
          description: "The event was added to the import job"
        400:
          description: "Invalid json message sent"
        404:
          description: "InstanceId does not match any import jobs"
        500:
          description: "Failed to process the request due to an internal error"
  /import/{instanceId}/state:
    put:
      tags:
      - "Internal Interface"
      summary: "Update the state of the import job"
      description: |
        Update the state of the import job. The following states are valid.
        * Created - The job has been created (Default state when created)
        * Inprogress - The dataset is being converted and ingested into a store
        * Completed - The dataset has been completed
        * Failed - The dataset has failed to be completed. See the events messages
      parameters:
      - $ref: '#/parameters/instanceId'
      - $ref: '#/parameters/state'
      produces:
      - "application/json"
      security:
      - InternalAPIKey: []
      responses:
        200:
          description: "The import state has been updated"
        404:
          description: "InstanceId does not match any import jobs"
        500:
          description: "Failed to process the request due to an internal error"
  /import/{instanceId}/dimensions:
    put:
      tags:
      - "Internal Interface"
      summary: "Add a dimension for the import job"
      description: |
        Add a dimension from the obervations found in the V3 data. To create a dimension the following items are needed;
        * nodeName - The name of the node eg (instanceId)-(dimension).(value)
        * nodeId - The unique id for this node
      parameters:
      - $ref: '#/parameters/instanceId'
      - $ref: '#/parameters/dimension'
      produces:
      - "application/json"
      security:
      - InternalAPIKey: []
      responses:
        200:
          description: "The dimension was added"
        404:
          description: "InstanceId does not match any import jobs"
        500:
          description: "Failed to process the request due to an internal error"
    get:
      tags:
      - "Internal Interface"
      summary: "Get all dimensions from an imported job"
      description: "Get all the dimensions within an import job"
      parameters:
      - $ref: '#/parameters/instanceId'
      produces:
      - "application/json"
      security:
      - InternalAPIKey: []
      responses:
        200:
          description: "Return a list of dimensions"
          schema:
            $ref: '#/definitions/Dimensions'
        404:
          description: "InstanceId does not match any import jobs"
        500:
          description: "Failed to process the request due to an internal error"
definitions:
  JobInstance:
    type: object
    description: "A object returned when an import job is created"
    properties:
      instanceId:
        type: string
        description: "A unique id for an import job"
  ImportJob:
    type: object
    description: "A object used to create a import job"
    properties:
      dataset:
        type: string
        description: "The name of the dataset"
  ImportJobState:
    type: object
    properties:
      instanceId:
        type: string
        description: "A unique id for an import job"
      dataset:
        type: string
        description: "The name of the dataset"
      s3Files:
        type: array
        description: "A list of all S3 files to be used for the import job"
        items:
          $ref: '#/definitions/S3File'
      state:
        type: string
        description: |
          The state of the import job, this can be;
          * Created - The job has been created (Default state when created)
          * Inprogress - The dataset is being converted and ingested into a store
          * Completed - The dataset has been completed
          * Failed - The dataset has failed to be completed. See the events messages
      events:
        type: array
        description: "A list of events took place for this job"
        items:
          $ref: '#/definitions/ImportEvent'
      lastUpdated:
        type: string
        description: "The last time an event happened"
  ImportEvent:
    type: object
    properties:
      type:
        type: string
        description: |
          The type of event, this can be;
          * Info - for an information event
          * Error - for an error event
      time:
        type: string
        description: "The time of the event in ISO 8601 format"
      message:
        type: string
        description: "A description of the event"
      messageOffset:
        type: string
        description: "The kafka message offset (Used to locate the kafka message)"
  ImportJobStates:
    type: object
    description: "A paginated list of import jobs"
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/ImportJobState'
      numberOfPages:
        type: integer
        description: "The number of pages based of the size requested"
  State:
    type: object
    description: "A object used to update the state an import job"
    properties:
      state:
        type: string
        description: |
          The state to set the job, this can be;
          * Created - The job has been created (Default state when created)
          * Inprogress - The dataset is being converted and ingested into a store
          * Completed - The dataset has been completed
          * Failed - The dataset has failed to be completed. See the events messages
  Dimension:
    type: object
    description: "A dimension object"
    properties:
      nodeName:
        description: "The name of the node (instanceId-dimension.value)."
        type: string
      value:
        description: "The value of the dimension"
        type: string
      nodeId:
        description: "Graph database node Id"
        type: string
  Dimensions:
    type: object
    properties:
      instanceId:
        type: string
        description: "The instanceId of the import job"
      items:
        type: array
        description: "A list of all dimensions within an import job"
        items:
          $ref: '#/definitions/Dimension'
  S3File:
    type: object
    properties:
      aliasName:
        description: "An alias name for the file"
        type: string
      URL:
        description: "The full S3 path including zone, and bucket"
        type: string