// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-import-api/config"
	"github.com/ONSdigital/dp-import-api/datastore"
	"github.com/ONSdigital/dp-import-api/service"
	"github.com/ONSdigital/dp-kafka"
	"net/http"
	"sync"
)

var (
	lockInitialiserMockDoGetHTTPServer     sync.RWMutex
	lockInitialiserMockDoGetHealthCheck    sync.RWMutex
	lockInitialiserMockDoGetKafkaProducer  sync.RWMutex
	lockInitialiserMockDoGetMongoDataStore sync.RWMutex
)

// Ensure, that InitialiserMock does implement service.Initialiser.
// If this is not the case, regenerate this file with moq.
var _ service.Initialiser = &InitialiserMock{}

// InitialiserMock is a mock implementation of service.Initialiser.
//
//     func TestSomethingThatUsesInitialiser(t *testing.T) {
//
//         // make and configure a mocked service.Initialiser
//         mockedInitialiser := &InitialiserMock{
//             DoGetHTTPServerFunc: func(bindAddr string, router http.Handler) service.HTTPServer {
// 	               panic("mock out the DoGetHTTPServer method")
//             },
//             DoGetHealthCheckFunc: func(cfg *config.Configuration, buildTime string, gitCommit string, version string) (service.HealthChecker, error) {
// 	               panic("mock out the DoGetHealthCheck method")
//             },
//             DoGetKafkaProducerFunc: func(ctx context.Context, kafkaBrokers []string, topic string, envMax int) (kafka.IProducer, error) {
// 	               panic("mock out the DoGetKafkaProducer method")
//             },
//             DoGetMongoDataStoreFunc: func(cfg *config.Configuration) (datastore.DataStorer, error) {
// 	               panic("mock out the DoGetMongoDataStore method")
//             },
//         }
//
//         // use mockedInitialiser in code that requires service.Initialiser
//         // and then make assertions.
//
//     }
type InitialiserMock struct {
	// DoGetHTTPServerFunc mocks the DoGetHTTPServer method.
	DoGetHTTPServerFunc func(bindAddr string, router http.Handler) service.HTTPServer

	// DoGetHealthCheckFunc mocks the DoGetHealthCheck method.
	DoGetHealthCheckFunc func(cfg *config.Configuration, buildTime string, gitCommit string, version string) (service.HealthChecker, error)

	// DoGetKafkaProducerFunc mocks the DoGetKafkaProducer method.
	DoGetKafkaProducerFunc func(ctx context.Context, kafkaBrokers []string, topic string, envMax int) (kafka.IProducer, error)

	// DoGetMongoDataStoreFunc mocks the DoGetMongoDataStore method.
	DoGetMongoDataStoreFunc func(cfg *config.Configuration) (datastore.DataStorer, error)

	// calls tracks calls to the methods.
	calls struct {
		// DoGetHTTPServer holds details about calls to the DoGetHTTPServer method.
		DoGetHTTPServer []struct {
			// BindAddr is the bindAddr argument value.
			BindAddr string
			// Router is the router argument value.
			Router http.Handler
		}
		// DoGetHealthCheck holds details about calls to the DoGetHealthCheck method.
		DoGetHealthCheck []struct {
			// Cfg is the cfg argument value.
			Cfg *config.Configuration
			// BuildTime is the buildTime argument value.
			BuildTime string
			// GitCommit is the gitCommit argument value.
			GitCommit string
			// Version is the version argument value.
			Version string
		}
		// DoGetKafkaProducer holds details about calls to the DoGetKafkaProducer method.
		DoGetKafkaProducer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// KafkaBrokers is the kafkaBrokers argument value.
			KafkaBrokers []string
			// Topic is the topic argument value.
			Topic string
			// EnvMax is the envMax argument value.
			EnvMax int
		}
		// DoGetMongoDataStore holds details about calls to the DoGetMongoDataStore method.
		DoGetMongoDataStore []struct {
			// Cfg is the cfg argument value.
			Cfg *config.Configuration
		}
	}
}

// DoGetHTTPServer calls DoGetHTTPServerFunc.
func (mock *InitialiserMock) DoGetHTTPServer(bindAddr string, router http.Handler) service.HTTPServer {
	if mock.DoGetHTTPServerFunc == nil {
		panic("InitialiserMock.DoGetHTTPServerFunc: method is nil but Initialiser.DoGetHTTPServer was just called")
	}
	callInfo := struct {
		BindAddr string
		Router   http.Handler
	}{
		BindAddr: bindAddr,
		Router:   router,
	}
	lockInitialiserMockDoGetHTTPServer.Lock()
	mock.calls.DoGetHTTPServer = append(mock.calls.DoGetHTTPServer, callInfo)
	lockInitialiserMockDoGetHTTPServer.Unlock()
	return mock.DoGetHTTPServerFunc(bindAddr, router)
}

// DoGetHTTPServerCalls gets all the calls that were made to DoGetHTTPServer.
// Check the length with:
//     len(mockedInitialiser.DoGetHTTPServerCalls())
func (mock *InitialiserMock) DoGetHTTPServerCalls() []struct {
	BindAddr string
	Router   http.Handler
} {
	var calls []struct {
		BindAddr string
		Router   http.Handler
	}
	lockInitialiserMockDoGetHTTPServer.RLock()
	calls = mock.calls.DoGetHTTPServer
	lockInitialiserMockDoGetHTTPServer.RUnlock()
	return calls
}

// DoGetHealthCheck calls DoGetHealthCheckFunc.
func (mock *InitialiserMock) DoGetHealthCheck(cfg *config.Configuration, buildTime string, gitCommit string, version string) (service.HealthChecker, error) {
	if mock.DoGetHealthCheckFunc == nil {
		panic("InitialiserMock.DoGetHealthCheckFunc: method is nil but Initialiser.DoGetHealthCheck was just called")
	}
	callInfo := struct {
		Cfg       *config.Configuration
		BuildTime string
		GitCommit string
		Version   string
	}{
		Cfg:       cfg,
		BuildTime: buildTime,
		GitCommit: gitCommit,
		Version:   version,
	}
	lockInitialiserMockDoGetHealthCheck.Lock()
	mock.calls.DoGetHealthCheck = append(mock.calls.DoGetHealthCheck, callInfo)
	lockInitialiserMockDoGetHealthCheck.Unlock()
	return mock.DoGetHealthCheckFunc(cfg, buildTime, gitCommit, version)
}

// DoGetHealthCheckCalls gets all the calls that were made to DoGetHealthCheck.
// Check the length with:
//     len(mockedInitialiser.DoGetHealthCheckCalls())
func (mock *InitialiserMock) DoGetHealthCheckCalls() []struct {
	Cfg       *config.Configuration
	BuildTime string
	GitCommit string
	Version   string
} {
	var calls []struct {
		Cfg       *config.Configuration
		BuildTime string
		GitCommit string
		Version   string
	}
	lockInitialiserMockDoGetHealthCheck.RLock()
	calls = mock.calls.DoGetHealthCheck
	lockInitialiserMockDoGetHealthCheck.RUnlock()
	return calls
}

// DoGetKafkaProducer calls DoGetKafkaProducerFunc.
func (mock *InitialiserMock) DoGetKafkaProducer(ctx context.Context, kafkaBrokers []string, topic string, envMax int) (kafka.IProducer, error) {
	if mock.DoGetKafkaProducerFunc == nil {
		panic("InitialiserMock.DoGetKafkaProducerFunc: method is nil but Initialiser.DoGetKafkaProducer was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		KafkaBrokers []string
		Topic        string
		EnvMax       int
	}{
		Ctx:          ctx,
		KafkaBrokers: kafkaBrokers,
		Topic:        topic,
		EnvMax:       envMax,
	}
	lockInitialiserMockDoGetKafkaProducer.Lock()
	mock.calls.DoGetKafkaProducer = append(mock.calls.DoGetKafkaProducer, callInfo)
	lockInitialiserMockDoGetKafkaProducer.Unlock()
	return mock.DoGetKafkaProducerFunc(ctx, kafkaBrokers, topic, envMax)
}

// DoGetKafkaProducerCalls gets all the calls that were made to DoGetKafkaProducer.
// Check the length with:
//     len(mockedInitialiser.DoGetKafkaProducerCalls())
func (mock *InitialiserMock) DoGetKafkaProducerCalls() []struct {
	Ctx          context.Context
	KafkaBrokers []string
	Topic        string
	EnvMax       int
} {
	var calls []struct {
		Ctx          context.Context
		KafkaBrokers []string
		Topic        string
		EnvMax       int
	}
	lockInitialiserMockDoGetKafkaProducer.RLock()
	calls = mock.calls.DoGetKafkaProducer
	lockInitialiserMockDoGetKafkaProducer.RUnlock()
	return calls
}

// DoGetMongoDataStore calls DoGetMongoDataStoreFunc.
func (mock *InitialiserMock) DoGetMongoDataStore(cfg *config.Configuration) (datastore.DataStorer, error) {
	if mock.DoGetMongoDataStoreFunc == nil {
		panic("InitialiserMock.DoGetMongoDataStoreFunc: method is nil but Initialiser.DoGetMongoDataStore was just called")
	}
	callInfo := struct {
		Cfg *config.Configuration
	}{
		Cfg: cfg,
	}
	lockInitialiserMockDoGetMongoDataStore.Lock()
	mock.calls.DoGetMongoDataStore = append(mock.calls.DoGetMongoDataStore, callInfo)
	lockInitialiserMockDoGetMongoDataStore.Unlock()
	return mock.DoGetMongoDataStoreFunc(cfg)
}

// DoGetMongoDataStoreCalls gets all the calls that were made to DoGetMongoDataStore.
// Check the length with:
//     len(mockedInitialiser.DoGetMongoDataStoreCalls())
func (mock *InitialiserMock) DoGetMongoDataStoreCalls() []struct {
	Cfg *config.Configuration
} {
	var calls []struct {
		Cfg *config.Configuration
	}
	lockInitialiserMockDoGetMongoDataStore.RLock()
	calls = mock.calls.DoGetMongoDataStore
	lockInitialiserMockDoGetMongoDataStore.RUnlock()
	return calls
}
