// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package testjob

import (
	"github.com/ONSdigital/dp-import-api/models"
	"sync"
)

var (
	lockJobQueueMockQueue sync.RWMutex
)

// JobQueueMock is a mock implementation of JobQueue.
//
//     func TestSomethingThatUsesJobQueue(t *testing.T) {
//
//         // make and configure a mocked JobQueue
//         mockedJobQueue := &JobQueueMock{
//             QueueFunc: func(job *models.ImportData) error {
// 	               panic("TODO: mock out the Queue method")
//             },
//         }
//
//         // TODO: use mockedJobQueue in code that requires JobQueue
//         //       and then make assertions.
//
//     }
type JobQueueMock struct {
	// QueueFunc mocks the Queue method.
	QueueFunc func(job *models.ImportData) error

	// calls tracks calls to the methods.
	calls struct {
		// Queue holds details about calls to the Queue method.
		Queue []struct {
			// Job is the job argument value.
			Job *models.ImportData
		}
	}
}

// Queue calls QueueFunc.
func (mock *JobQueueMock) Queue(job *models.ImportData) error {
	if mock.QueueFunc == nil {
		panic("moq: JobQueueMock.QueueFunc is nil but JobQueue.Queue was just called")
	}
	callInfo := struct {
		Job *models.ImportData
	}{
		Job: job,
	}
	lockJobQueueMockQueue.Lock()
	mock.calls.Queue = append(mock.calls.Queue, callInfo)
	lockJobQueueMockQueue.Unlock()
	return mock.QueueFunc(job)
}

// QueueCalls gets all the calls that were made to Queue.
// Check the length with:
//     len(mockedJobQueue.QueueCalls())
func (mock *JobQueueMock) QueueCalls() []struct {
	Job *models.ImportData
} {
	var calls []struct {
		Job *models.ImportData
	}
	lockJobQueueMockQueue.RLock()
	calls = mock.calls.Queue
	lockJobQueueMockQueue.RUnlock()
	return calls
}
