// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package testjob

import (
	"github.com/ONSdigital/dp-import-api/models"
	"sync"
)

var (
	lockQueueMockQueue sync.RWMutex
)

// QueueMock is a mock implementation of Queue.
//
//     func TestSomethingThatUsesQueue(t *testing.T) {
//
//         // make and configure a mocked Queue
//         mockedQueue := &QueueMock{
//             QueueFunc: func(job *models.ImportData) error {
// 	               panic("TODO: mock out the Queue method")
//             },
//         }
//
//         // TODO: use mockedQueue in code that requires Queue
//         //       and then make assertions.
//
//     }
type QueueMock struct {
	// QueueFunc mocks the Queue method.
	QueueFunc func(job *models.ImportData) error

	// calls tracks calls to the methods.
	calls struct {
		// Queue holds details about calls to the Queue method.
		Queue []struct {
			// Job is the job argument value.
			Job *models.ImportData
		}
	}
}

// Queue calls QueueFunc.
func (mock *QueueMock) Queue(job *models.ImportData) error {
	if mock.QueueFunc == nil {
		panic("moq: QueueMock.QueueFunc is nil but Queue.Queue was just called")
	}
	callInfo := struct {
		Job *models.ImportData
	}{
		Job: job,
	}
	lockQueueMockQueue.Lock()
	mock.calls.Queue = append(mock.calls.Queue, callInfo)
	lockQueueMockQueue.Unlock()
	return mock.QueueFunc(job)
}

// QueueCalls gets all the calls that were made to Queue.
// Check the length with:
//     len(mockedQueue.QueueCalls())
func (mock *QueueMock) QueueCalls() []struct {
	Job *models.ImportData
} {
	var calls []struct {
		Job *models.ImportData
	}
	lockQueueMockQueue.RLock()
	calls = mock.calls.Queue
	lockQueueMockQueue.RUnlock()
	return calls
}
