---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.10.1

inputs:
  - name: dp-import-api
    path: go/src/github.com/ONSdigital/dp-import-api

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/dp-import-api/ci/scripts/build.sh
