---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.17.1

inputs:
  - name: dp-import-api

outputs:
  - name: build

run:
  path: dp-import-api/ci/scripts/build.sh
